import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'tailwindcss/tailwind.css'; 
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import StoreProvider from "@/providers/StoreProvider";
import ToasterProvider from "@/providers/ToasterProvider";
import { ThemeProvider } from "@/components/theme-provider"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ToasterProvider />
          <StoreProvider />
          {children}
        </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
